# Generated by Django 6.0 on 2025-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_favourite_added_at_alter_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='name',
            field=models.CharField(default='default', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfavourite',
            name='name',
            field=models.CharField(default='lala', verbose_name='Название'),
            preserve_default=False,
        ),
    ]
